server:
  port: 8080
  servlet:
    context-path: /api

spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/debt_manager?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: Ga@12345
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  
  jackson:
    property-naming-strategy: SNAKE_CASE

jwt:
  secret: mySecretKey123456789012345678901234567890123456789012345678901234567890
  expiration: 86400000 # 24 hours

logging:
  level:
    com.debtmanager: DEBUG
